const ROUTES = {
  ROOT: "/",
  ABOUT: "/about",
  CARDS: "/cards",
  SIGNUP: "/signup",
  LOGIN: "/login",
  MY_CARDS: "/my-cards",
  FAV_CARDS: "/fav-cards",
  SANDBOX: "/sandbox",
  CARD_DETAILS: "/card-info",
  CARD_EDIT: "/card-edit",
  CREATE_CARD: "/create-card",
  USER_EDIT: "/user-edit",
  USER_PROFILE: "/user-profile",
  CRM: "/crm",
};

export const SANDBOX_ROUTES = {
  COMPONENT: "component",
  STYLES: "styles",
  STYLE_MODULE: "style-module",
  STYLES_2: "styles2",
  TEMPLATE: "template",
  LOGIC: "logic",
  SANDBOX_COMPONENT: "sandbox-component",
  STRING_INTERPOLATION: "string-interpolation",
  BABEL: "babel",
  EVENTS: "events",
  ONCLICK: "onclick",
  RAISING_EVENTS: "raising-events",

  CONDITIONAL: "Conditional",
  LOOPS: "loops",
  MUI_COMPONENT: "mui-components",
  DATA_DISPLAY: "data-display",
  LAYOUT: "layout",
  NAVIGATION: "navigation",
  MUI_BUTTON: "mui-button",
  MUI_DIVIDER: "mui-divider",
  MUI_TYPOGRAPHY: "mui-typography",
  MUI_BOX: "mui-box",
  MUI_CONTAINER: "mui-container",
  MUI_GRID: "mui-grid",
  MUI_STACK: "mui-stack",
  MUI_APP_BAR: "mui-app-bar",
  MUI_BOTTOM_NAVIGATION: "mui-bottom-navigation",
  CUSTOM: "custom",
  CUSTOM_NAME: "custom-name",
};
export default ROUTES;
